build:
  stage: build
  image: node:10.12.0
  cache:
    paths:
      - node_modules/
  only:
    - master
  script:
    - pwd
    - npm set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
    - rm -rf /home/web/vue.web
    - cp -rf ./dist /home/web/vue.web

  artifacts:  
    expire_in: 1 week
    paths:
      - dist
  tags:
      - dev      
