apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: test
  labels:
    name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
      - name: demo
        image: 	registry.cn-shenzhen.aliyuncs.com/zjzhang/k8s:demo
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        # 监控检查 Liveness探针
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          timeoutSeconds: 5