apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30001
  selector:
    name: mysql

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test
  labels:
    name: mysql
spec:
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '111111'
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /val/lib/mysql
      volumes:
      - name:  mysql-storage
        hostPath: 
          path: /val/lib/mysql