version: '3'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:11.1.4'
      container_name: gitlab
      restart: unless-stopped
      privileged: true
      hostname: '10.1.71.45'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://10.1.71.45/'
          gitlab_rails['gitlab_shell_ssh_port'] = 1022
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
      ports:
        - '80:80'
        - '443:443'
        - '1022:22'
      networks:
        - gitlab_default  
      volumes:
        - /git/gitlab/data:/var/opt/gitlab
        - /git/gitlab/config:/etc/gitlab
        - /git/gitlab/logs:/var/log/gitlab

networks:
  gitlab_default: