version: "3"
services:
  mall-tiny:
    build: .
    image: mall-tiny
    environment:
      - TZ=Asia/Shanghai
    container_name: mall-tiny
    volumes:
      - /home/mall-tiny/logs:/var/logs
    ports:
      - "8080:8080"
    networks:
      - mysql_default
      - redis_default
networks:
  mysql_default:
    external: true
  redis_default:
    external: true
