version: '3'
services:
  ncp.api.:
    build: .
    image: ncp.api
    container_name: ncp.api
    volumes:
      - "./logs:/app/logs"
      - "./appsettings.json:/app/appsettings.json"
    ports: 
      - 6003:5000
    logging:
      driver: "json-file"
