version: '3'
services:
  summer.api:
    build: .
    image: summer.api
    environment:
      - TZ=Asia/Shanghai
    container_name: summer.api
    volumes:
      - /home/summer.api/bin/logs:/app/logs
      - /home/summer.api/bin/config/appsettings.json:/app/appsettings.json
    ports: 
      - '5000:80'
    networks:
      - apiNet
networks:
  apiNet: