version: "3"
services:
  nginx:
    image: docker.io/nginx
    container_name: nginx
    volumes:
      - /home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - /home/nginx/logs:/var/log/nginx 
      - /home/web:/home/web 
    ports: 
      - "80:80"
      - "9000:9000"
      - "9001:9001"
    networks:
      - nginxNet

networks:
    nginxNet: