version: "3"
services:
  nginx:
    image: docker.io/nginx
    container_name: nginx
    restart: always
    volumes:
      - /iflymed/nginx/nginx.conf:/etc/nginx/nginx.conf     
      - /iflymed/nginx/logs:/var/log/nginx   
      - /iflymed/nginx/ca:/iflymed/nginx/ca
      - /iflymed/ncp:/iflymed/ncp
    ports: 
      - "80:80"
      - "443:443"       
      - "5001:5001"   
      - "5002:5002"
    logging:
      driver: "json-file"
      options:
        max-size: '12m'
        max-file: '5'      
    networks:
      - apiNet

networks:
    apiNet: