version: "3"
services:
  nginx:
    #image: docker.io/nginx
    image: hub.iflytek.com/zlyy-public/nginx:1.17.10
    container_name: nginx
    restart: always
    volumes:
      - /home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/logs:/var/log/nginx
      - /home/web:/home/web
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
