version: "3"
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/redis/data:/data
      - /home/redis/logs:/logs
    command: redis-server /etc/redis/redis.conf
